# cSpell:disable
name: ansible-role-podman
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip==24.3.1
  - pip:
      - ansible==11.1.0
      - molecule-plugins[podman]==23.6.0
      - pytest-testinfra==10.1.1
      - pre-commit==4.0.1
