# cSpell:disable
namespace: pycodebe
name: podman
version: 0.0.1
readme: README.md
authors:
  - pycodebe
description: |
    This role manages Podman installation, configuration, and lifecycle across different Linux distributions. It provides
    functionality to install, uninstall, update, and verify Podman installation with cross-platform support
repository: https://github.com/pycodebe/ansible-role-podman.git
build_ignore:
  - '*.pyc'
  - '.gitignore'
  - '.ansible-lint'
  - '.env'
  - '.pre-commit-config.yaml'
  - 'environment.yml'
