---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Podman
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/tasks/install.yml"
    - name: Uninstall Podman
      ansible.builtin.include_tasks:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/tasks/uninstall.yml"
