---

- name: Include check.yml
  ansible.builtin.include_tasks: check.yml

- name: Include install.yml
  ansible.builtin.include_tasks: install.yml
  when:
    - podman_action == 'install'
    - not podman_installed

- name: Include install.yml and configure registry.yml
  ansible.builtin.include_tasks: install_and_configure_registry.yml
  when:
    - podman_action == 'install_and_configure_registry'
    - not podman_installed

- name: Include uninstall.yml
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - podman_action == 'uninstall'
    - podman_installed

- name: Include update.yml
  ansible.builtin.include_tasks: update.yml
  when:
    - podman_action == 'update'
    - podman_installed

- name: Include configure_registry.yml
  ansible.builtin.include_tasks: configure_registry.yml
  when:
    - podman_action == 'configure_registry'
    - podman_installed
